#!/bin/bash

wait_for_postgres() {
  until docker-compose run db psql -h db -U postgres -c '\l' >/dev/null 2>&1; do
    echo "Postgres is unavailable - sleeping"
    sleep 1
  done
}

migrate() {
  docker-compose run db psql -h db -U postgres -a -f /usr/src/app/migrations/$1
}

docker-compose up -d db && wait_for_postgres

if [ $# -eq 0 ]; then
  for migration in `ls backend/migrations/`; do
      cat backend/migrations/$migration >> backend/migrations/migrate.sql
  done
  migrate migrate.sql
  rm backend/migrations/migrate.sql
else
  echo "Migrating $1"
  migrate $1
fi

